### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kinbod** [bbossgroups/bboss-elastic-tran#3]
BBossStarter  line 110   temConf.setQueryfetchsize(db.getJdbcFetchSize()!=null? Interger.parseInt(db.getInitSize():0);   

has bug  

corrent: temConf.setQueryfetchsize(db.getJdbcFetchSize()!=null? Interger.parseInt(db.getJdbcFetchSize():0) : Interger.parseInt(db.getInitSize():0);

**Comment by yin-bp** [comment]
@kinbod Hi，问题已经修复
